version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      # MYSQL_DATABASE: "rest_with_spring_boot"
    ports:
      - "3306:3306"
    #    volumes:
    #      - /home/gdarlan/Documentos/cursos/byte-bank-alura/volumes:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge